swiftmailer:
    username: '%env(MAIL_USER)%'
    password: '%env(MAIL_PASSWORD)%'
    host: '%env(MAIL_SMTP_HOST)%'
    port: '%env(MAIL_PORT)%'
    encryption: ssl
    auth-mode: login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false