version: '3.7'
services:
  nginx:
    image: nginx:1.12.1
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/html"
    networks:
      - news_portal_docker_network
  php:
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html"
    networks:
      - news_portal_docker_network
  db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - "8800:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: news_portal
        MYSQL_USER: news_portal
        MYSQL_PASSWORD: password
      networks:
        news_portal_docker_network:
          ipv4_address: 192.168.200.8
networks:
  news_portal_docker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/26