index:
    path: /
    controller: App\Controller\IndexController::index
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
    methods: GET
register:
    path: /register
    controller: App\Controller\RegistrationController::register
activate-account:
    path: /activate-account/{token}
    controller: App\Controller\RegistrationController::activateAccount
