index:
    path: /
    controller: App\Controller\IndexController::index

# Security

login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
    methods: GET
register:
    path: /register
    controller: App\Controller\RegistrationController::register
activate-account:
    path: /activate-account/{token}
    controller: App\Controller\RegistrationController::activateAccount

# User
my-profile:
    path: /my-profile
    methods: GET
    controller: App\Controller\UserController::myProfile
view-author:
    path: /author/{author}
    methods: GET
    controller: App\Controller\UserController::authorView


# Post
create-post:
    path: /create-post
    methods: GET|POST
    controller: App\Controller\PostController::createPost
view-post:
    path: /post/{post}
    methods: GET
    controller: App\Controller\PostController::view
view-template-post:
    path: /post/{post}/template
    methods: GET
    controller: App\Controller\PostController::viewTemplate
update-post:
    path: /post/{post}/update
    methods: GET|POST
    controller: App\Controller\PostController::update
send-post-to-moderation:
    path: /post/{post}/moderate-post
    methods: POST
    controller: App\Controller\PostController::moderatePost

# Api
api-get-all-tags:
    path: /api/tag
    methods: GET
    controller: App\Controller\Api\TagController::index
api-post-rating-up:
    path: /api/post/rating-up/{post}
    methods: POST
    controller: App\Controller\Api\PostController::ratingUp
api-post-rating-down:
    path: /api/post/rating-up/{post}
    methods: POST
    controller: App\Controller\Api\PostController::ratingDown