index:
    path: /
    controller: App\Controller\IndexController::index

# Security

login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
    methods: GET
register:
    path: /register
    controller: App\Controller\RegistrationController::register
activate-account:
    path: /activate-account/{token}
    controller: App\Controller\RegistrationController::activateAccount

# User
my-profile:
    path: /my-profile
    methods: GET
    controller: App\Controller\UserController::myProfile

# Post
create-post:
    path: /create-post
    methods: GET|POST
    controller: App\Controller\PostController::createPost
view-post:
    path: /post/{post}
    methods: GET
    controller: App\Controller\PostController::view


# API
